jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - uses: samueldr/lix-gha-installer-action@f526e761e1ad201b0f4231f61a2a569f17bcc2ac # main
    - uses: raitobezarius/setup-nix-cache-action@aae701971c1d9979d7c2f4197db4ecf6d4acc79c # retries
      with:
        substituters: s3://test-ovh-s3?endpoint=https://s3.gra.io.cloud.ovh.net&region=gra&compression=zstd&parallel-compression=true
        secret_keys: ${{ secrets.NIX_SIGNING_PRIVATE_KEY }}
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        retry_attempts: 5
    - name: Build tests
      run: nix-build -A tests
name: '[Sécurix] Test suite'
on:
  pull_request:
  push:
    branches:
    - main
